//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imogen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfileUrlHash {
            get {
                return ((string)(this["ProfileUrlHash"]));
            }
            set {
                this["ProfileUrlHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfileSrcUrlHash {
            get {
                return ((string)(this["ProfileSrcUrlHash"]));
            }
            set {
                this["ProfileSrcUrlHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfileLinkUrlHash {
            get {
                return ((string)(this["ProfileLinkUrlHash"]));
            }
            set {
                this["ProfileLinkUrlHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Dave\\Pictures\\Imogen")]
        public string FileSavePath {
            get {
                return ((string)(this["FileSavePath"]));
            }
            set {
                this["FileSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProfileReportedOn {
            get {
                return ((string)(this["ProfileReportedOn"]));
            }
            set {
                this["ProfileReportedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfileReportNumber {
            get {
                return ((string)(this["ProfileReportNumber"]));
            }
            set {
                this["ProfileReportNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfilePossibleFileName1 {
            get {
                return ((string)(this["ProfilePossibleFileName1"]));
            }
            set {
                this["ProfilePossibleFileName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfilePossibleFileName2 {
            get {
                return ((string)(this["ProfilePossibleFileName2"]));
            }
            set {
                this["ProfilePossibleFileName2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserUsername {
            get {
                return ((string)(this["UserUsername"]));
            }
            set {
                this["UserUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPassword {
            get {
                return ((string)(this["UserPassword"]));
            }
            set {
                this["UserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoginRememberMe {
            get {
                return ((bool)(this["LoginRememberMe"]));
            }
            set {
                this["LoginRememberMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2" +
            "228.0 Safari/537.36")]
        public string RestrictedBrowserUserAgent {
            get {
                return ((string)(this["RestrictedBrowserUserAgent"]));
            }
            set {
                this["RestrictedBrowserUserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SessionSeconds {
            get {
                return ((double)(this["SessionSeconds"]));
            }
            set {
                this["SessionSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SessionSecondsTotal {
            get {
                return ((double)(this["SessionSecondsTotal"]));
            }
            set {
                this["SessionSecondsTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfileLinkUrl {
            get {
                return ((string)(this["ProfileLinkUrl"]));
            }
            set {
                this["ProfileLinkUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfileSrcUrl {
            get {
                return ((string)(this["ProfileSrcUrl"]));
            }
            set {
                this["ProfileSrcUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfileUrl {
            get {
                return ((string)(this["ProfileUrl"]));
            }
            set {
                this["ProfileUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string ProfileLinkUrlARCRating {
            get {
                return ((string)(this["ProfileLinkUrlARCRating"]));
            }
            set {
                this["ProfileLinkUrlARCRating"] = value;
            }
        }

        public string ImagePath { get; internal set; }
        public int UserId { get; internal set; }
        public bool SrcSaved { get; internal set; }
    }
}
