//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imogen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentReport
    {
        public int pid { get; set; }
        public int ReportNumber { get; set; }
        public System.DateTime ReportStartedOn { get; set; }
        public System.DateTime ReportEndedOn { get; set; }
        public System.DateTime ReportedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int ReportedBy { get; set; }
        public int ProcessingBy { get; set; }
        public string PageUrl { get; set; }
        public string PageUrlHash { get; set; }
        public string SrcUrl { get; set; }
        public string SrcUrlHash { get; set; }
        public string LinkUrl { get; set; }
        public string LinkUrlHash { get; set; }
        public string TrueLinkUrl { get; set; }
        public string TrueLinkUrlHash { get; set; }
        public string PageUrlFilename { get; set; }
        public string SrcUrlFilename { get; set; }
        public string LinkUrlFilename { get; set; }
        public string TrueLinkUrlFilename { get; set; }
        public Nullable<int> SrcUrlARCXRating { get; set; }
        public Nullable<int> LinkUrlARCXRating { get; set; }
        public string ImagePath { get; set; }
        public double ReportSessionTime { get; set; }
        public Nullable<bool> ReportOverDue { get; set; }
        public Nullable<bool> ReportProcessed { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual EUReported EUReported { get; set; }
    }
}
