//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imogen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EUReported
    {
        public int id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool Processed { get; set; }
        public string PageUrl { get; set; }
        public string PageUrlHash { get; set; }
        public string SrcUrl { get; set; }
        public string SrcUrlHash { get; set; }
        public string LinkUrl { get; set; }
        public string LinkUrlHash { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
