//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imogen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceARC
    {
        public int pid { get; set; }
        public Nullable<int> AId { get; set; }
        public Nullable<int> RId { get; set; }
        public Nullable<int> CId { get; set; }
        public int FaceId { get; set; }
    
        public virtual A A { get; set; }
        public virtual C C { get; set; }
        public virtual Face Face { get; set; }
        public virtual R R { get; set; }
    }
}
