//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imogen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoneButNotForgottenLink
    {
        public int pid { get; set; }
        public int Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastCheckedOn { get; set; }
        public int ReportedBy { get; set; }
        public string SrcUrlHash { get; set; }
        public string LinkUrlHash { get; set; }
        public string TrueLinkUrlHash { get; set; }
    
        public virtual EUReported EUReported { get; set; }
        public virtual User User { get; set; }
    }
}
