//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imogen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JurisdictionNote
    {
        public int pid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<int> PreviousMessage { get; set; }
        public int AddedBy { get; set; }
        public Nullable<int> JurisdictionId { get; set; }
    
        public virtual Jurisidction Jurisidction { get; set; }
        public virtual User User { get; set; }
    }
}
