//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imogen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessingResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessingResult()
        {
            this.EUReporteds = new HashSet<EUReported>();
            this.Matedatas = new HashSet<Matedata>();
        }
    
        public int pid { get; set; }
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ASrcResultId { get; set; }
        public Nullable<int> CSrcResultId { get; set; }
        public Nullable<int> RSrcResultId { get; set; }
        public Nullable<int> ALinkResultId { get; set; }
        public Nullable<int> RLinkResultId { get; set; }
        public Nullable<int> CLinkResultId { get; set; }
        public int JurisdictionId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual A A { get; set; }
        public virtual A A1 { get; set; }
        public virtual C C { get; set; }
        public virtual C C1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EUReported> EUReporteds { get; set; }
        public virtual Jurisidction Jurisidction { get; set; }
        public virtual R R { get; set; }
        public virtual R R1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matedata> Matedatas { get; set; }
    }
}
