//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imogen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersSession
    {
        public int pid { get; set; }
        public int id { get; set; }
        public System.DateTime LoggedOnAt { get; set; }
        public Nullable<System.DateTime> loggedOffAt { get; set; }
        public double SessionSeconds { get; set; }
    
        public virtual User User { get; set; }
    }
}
